- name: configurar banner cisco
  hosts: CISCO
  connection: network_cli
  gather_facts: no

  tasks:
    - name: configurar login banner
      nxos_banner:
         banner: motd
         text: "{{ lookup('file', './banner.cfg') }}"
         state: present
